version: 2

registries:
  github-tenx:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.TENX_DEV_TOKEN}}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    registries:
      - github-tenx
    commit-message:
      prefix: "ci(deps): "
